name: release-docker
description: Releases the docker image to the appropriate channel
inputs:
  docker-token:
    description: The Docker token used for releasing the image
    required: true
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
outputs:
  release-url:
    description: The URL to the created release
    value: ${{ steps.get-release-url.outputs.url }}
runs:
  using: composite
  steps:
    - id: get-docker-metadata
      uses: ./.github/actions/helper/docker-metadata
    - id: release-docker
      shell: bash
      run: |
        export DOCKER_USERNAME=${{ steps.get-docker-metadata.outputs.image-namespace }}
        export DOCKER_PASSWORD=${{ inputs.docker-token }}
        cat ${{ inputs.release-dir }}/.releaserc.json
        (cd ${{ inputs.release-dir }}; npx semantic-release)
    - id: get-git-metadata
      uses: ./.github/actions/helper/git-metadata
    - id: clean-tag
      uses: ./.github/actions/helper/clear-git-tag
      with:
        git-tag: ${{ steps.get-git-metadata.outputs.current-tag }}
    - id: get-release-url
      shell: bash
      run: |
        if [ "${{ steps.get-git-metadata.outputs.current-tag }}" != "" ]; then
           echo "url=https://hub.docker.com/r/${{ steps.get-docker-metadata.outputs.image-namespace }}/${{ steps.get-docker-metadata.outputs.image-repository }}/tags?page=1&ordering=last_updated }}" >> $GITHUB_OUTPUT
        else
          echo "url=no-release" >> $GITHUB_OUTPUT
        fi
    - id: update-readme
      uses: peter-evans/dockerhub-description@v3
      if: github.ref_name == 'main' && steps.get-git-metadata.outputs.current-tag != ''
      with:
        username: ${{ steps.get-docker-metadata.outputs.image-namespace }}
        password: ${{ inputs.docker-token }}
        repository: ${{ steps.get-docker-metadata.outputs.image-namespace }}/${{ steps.get-docker-metadata.outputs.image-repository }}
        short-description: ${{ github.event.repository.description }}
        readme-filepath: README.md