site_name: iCloud Photos Sync
site_url: https://steilerdev.github.io/icloud-photos-sync/
site_description: Documentation for icloud-photos-sync by steilerDev
site_author: Frank Steiler
copyright: steilerDev
repo_url: https://github.com/steilerDev/icloud-photos-sync
edit_uri: ""
docs_dir: 'src'
site_dir: 'site'
nav:
  - 'Home': README.md
  - 'Get Started': get-started.md
  - 'User Guides':
    - 'CLI Reference': user-guides/cli.md
    - 'Common Warnings': user-guides/common-warnings.md
    - 'Sync Metrics': user-guides/sync-metrics.md
    - 'Error & Crash Reporting': user-guides/error-reporting.md
    - 'Security': user-guides/security.md
  - 'Development Resources':
    - 'Milestone Plan': https://github.com/steilerDev/icloud-photos-sync/milestones
    - 'Motivation': dev/motivation.md
    - 'iCloud API': dev/api.md
    - 'Local File Structure': dev/local-file-structure.md
    - 'TypeDoc Code Documentation': https://github.com/steilerDev/icloud-photos-sync/wiki/Exports
    - 'Test & Deployment':
      - 'Test Environment': dev/test-environment.md
      - 'Coverage': dev/coverage/index.html

theme:
  name: material
  logo: assets/icloud-photos-sync.svg
  favicon: assets/icloud-photos-sync.svg
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features: 
    - content.tabs.link
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
plugins:
  - search