name: release-docker-setup
description: Sets up the docker release environment
inputs:
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
  artifact-name:
    description: The name of the uploaded docker artifact
    required: false
    default: docker-artifact
runs:
  using: composite
  steps:
    - id: prepare-semantic-release
      uses: ./.github/actions/helper/prepare-semantic-release
      with:
        release-config-dir: ${{ github.action_path }}
        release-dir: ${{ inputs.release-dir }}
    - id: get-docker-metadata
      uses: ./.github/actions/helper/docker-metadata
    - id: configure-release
      shell: bash
      run: |
        cat ${{ inputs.release-dir }}/.releaserc.json |\
          jq 'del(.plugins[0][1].name)' |\
          jq '.plugins[0][1].name.namespace = "${{ steps.get-docker-metadata.outputs.image-namespace }}"' |\
          jq '.plugins[0][1].name.repository = "${{ steps.get-docker-metadata.outputs.image-repository }}"' |\
          jq '.plugins[0][1].name.tag = "${{ steps.get-docker-metadata.outputs.image-tag }}"' |\
          sponge ${{ inputs.release-dir }}/.releaserc.json
    - id: download-docker-artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: docker-artifact
    - id: setup-docker-artifact
      shell: bash
      run: docker load --input docker-artifact/docker-amd64.tar.gz