name: release-docker
description: Releases the npm package to the appropriate channel and updates the uploaded artifact
inputs:
  npm-token:
    description: The npm token used for releasing the package
    required: true
  artifact-name:
    description: The name of the uploaded app artifact
    required: false
    default: app-artifact
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
outputs:
  release-url:
    description: The URL to the created release
    value: ${{ steps.get-release-url.outputs.url }}
runs:
  using: composite
  steps:
    - id: release-app
      shell: bash
      run: |
        export NPM_TOKEN=${{ inputs.npm-token }}
        export NPM_CONFIG_PROVENANCE=true
        (cd ${{ inputs.release-dir }}; npx semantic-release)
    - id: get-git-metadata
      uses: ./.github/actions/helper/git-metadata
    - id: get-npm-metadata
      uses: ./.github/actions/helper/npm-metadata
      with:
        package: ${{ inputs.release-dir }}/app/package.json
    - id: package-artifact
      if: steps.get-git-metadata.outputs.current-tag != ''
      shell: bash
      run: mv ${{ inputs.release-dir }}/*.tgz npm-pack.tgz
    - id: upload-artifact
      if: steps.get-git-metadata.outputs.current-tag != ''
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: npm-pack.tgz
    - id: clean-tag
      uses: ./.github/actions/helper/clear-git-tag
      with:
        git-tag: ${{ steps.get-git-metadata.outputs.current-tag }}
    - id: get-release-url
      shell: bash
      run: |
        if [ "${{ steps.get-git-metadata.outputs.current-tag }}" != "" ]; then
          echo "url=https://www.npmjs.com/package/${{ steps.get-npm-metadata.outputs.name }}/v/${{ steps.get-npm-metadata.outputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "url=no-release" >> $GITHUB_OUTPUT
        fi